### ISSUE TITLE
Discord RPC

### ISSUE THREAD

**Issue by DMMaster636** [snesrev/zelda3#123]
### What feature do you want to get added? And how it will work?

Like the title says: a simple and nice RPC for discord would be cool.

**Comment by snesrev** [comment]
What's rpc

**Comment by DMMaster636** [comment]
> What's rpc
it's these lil things that some games have when launched
![image](https://user-images.githubusercontent.com/86197998/192111293-057d4533-f959-4dd9-9510-fb044c4c2909.png)

**Comment by FitzRoyX** [comment]
I think maybe the readme should clarify the scope of main repo features. I'm guessing this is fork territory because it connects to the internet. There will also be requests like achievements, multiplayer, randomization, balance changes, shaders, possibly other elaborate things that add dependencies and conflicting licenses.
