### ISSUE TITLE
Second Agahnim fight issue

### ISSUE THREAD

**Issue by Ninban** [snesrev/zelda3#19]
After getting hit in the penultimate boss fight, a weird thing happened. Agahnim was targeting Link seemingly off screen. A number of ancilla effects stopped occurring (boots dust, sword charge, boomerang, somaria block, arrows, bombs...) and I couldn't reflect Agahnim's balls.

I tried to save a snapshot using Shift+F1 to F10 but it didn't work (did I miss a compilation option?) and I wasn't running the ROM for verification so I only have this clip. Posting the clip in the meantime. I plan to try again by next Saturday with the ROM running along.

https://clips.twitch.tv/CorrectHeartlessHerbsTinyFace-9zVBJTp4LhGjejE3

**Comment by cassidoxa** [comment]
I've experienced this running the game without the ROM as well. My suspicion is that it has something to do with updating Link's coordinates or possibly quadrant following knockback. They may be getting zeroed out incorrectly somewhere. For me it happened at Aga two as well as other boss fights. Notice how this happens in the clip after getting hit by the balled energy projectile.

For me it happened in GT following a successful Moldorm bounce and I noticed some strange behavior all the way from the Moldorm room to Aga 2 including clipping through the blocks. The Link sprite also disappeared when walking left into the icy bumper room door from the Moldorm instead of doing the door transition animation. This is consistent with incorrect Link, scroll, or camera coordinates in the vanilla game or possibly an incorrect quadrant being set.

**Comment by snesrev** [comment]
This is not the same bug as the Freezor bug.

**Comment by keatongreve** [comment]
Here's a SAV you where you can drop in before the fight: https://drive.google.com/file/d/1wzg7KXIUHh4sOC15k8rYWjiBNwi00ScG/view?usp=sharing
I've only reproduced the issue twice, which is why I created a SAV during the fight: https://drive.google.com/file/d/1dXVuV6g4g2c6jYY2HASQfb_J_ZOxeUkX/view?usp=sharing

The ROM comparison doesn't seem to set anything off after loading that save (possibly intended if the emulator is given the same state).
I observed these issues:
1) enemies aiming offscreen similar to the bug report
2) enemy projectiles unable to damage me
3) unable to hit enemy projectiles (forgot to record this, but pretty sure it will happen if you load this save)


https://user-images.githubusercontent.com/596193/187827271-f68db2ff-f012-4574-92d2-e7e04d09c048.mp4

**Comment by snesrev** [comment]
Not sure which bug this is, but for some reason that savegame is out of sync. I'm not able to replay it with Ctrl-F1. They joypad commands aren't in sync.

**Comment by snesrev** [comment]
When you hit something with a spin attack the X coordinate was messed up.
