### ISSUE TITLE
Feature Request: Widescreen hack to show more of the map

### ISSUE THREAD

**Issue by UltraHDR** [snesrev/zelda3#37]
Something like https://www.youtube.com/watch?v=-moxxEjz5x4

**Comment by snesrev** [comment]
This will be extremely hard without a big rework.

**Comment by snesrev** [comment]
This will be very hard to do in a non-glitchy way without a big rework. Any idea how bsnes is doing it?

**Comment by UltraHDR** [comment]
I think it's similar to https://prilik.com/ANESE/wideNES.html were it records the screen and displays it. Given that the source code exists, a mod similar to https://github.com/VitorVilela7/wide-snes would be better  . Not saying it'll be an easy task....

**Comment by FitzRoyX** [comment]
A somewhat related topic that I won't create a new issue for is expanding vres to 240. SNES overscan masking is mostly a superficial limitation that no longer applies to modern screens. But to retain the ability to compare to rom, it would have to be made an ini option because several parts of the rendering code would have to be adjusted to work with it.

**Comment by mvacosta** [comment]
Been working on an implementation on a fork that might be out of scope for this project. But since the PPU is constrained to the same parameters as the SNES (which I presume is to keep things as accurate as possible), there's a lot of restrictions. The big one being OAM, which restricts X & Y positions to 8-bit values. And since all these values are kept on the RAM to have parity with the SNES, it's not as simple as making X & Y be bigger values.

The approach I took was to completely decouple OAM (and potentially the BGs & Windows) to keep it out of the SNES RAM. That gives OAM the freedom to be able to be expanded (and eventually implement the flags into their own bools, or potentially add new features such as opacity & rotation). This is why I mention it might be out of scope for this project.

It's been a lot of rework but on my fork, but I have decoupled OAM and integrated it into the PPU properly. There's bound to be bugs introduced somewhere but it's been pretty stable so far. I've even turned X & Y into uint16s without issue. There's still work to be done in expanding all the truncations in `sprite_main.c` and such, and a lot of testing to make sure all the sprites appear as expected, hah.

**Comment by UltraHDR** [comment]
A WIP PR is here https://github.com/snesrev/zelda3/pull/71

**Comment by UltraHDR** [comment]
Thanks @snesrev for making this the definitive edition!!!

**Comment by ArhumMK** [comment]
Sorry for replying to a closed issue but is it possible to improve the widescreen implementation so that the camera stops following  the player once you reach the end of a screen transition so that it does not show the black void?

So that instead of this
![The Legend of Zelda_ A Link to the Past 29_06_2023 11_19_24](https://github.com/snesrev/zelda3/assets/70807030/0155a2d3-26e6-42ba-9db3-afa333dd69aa)

The Camera stops following you horizontally around this position until you go beyond the next screen trigger.
![The Legend of Zelda_ A Link to the Past 29_06_2023 11_19_29](https://github.com/snesrev/zelda3/assets/70807030/f773b2e4-4383-401a-bd2a-44fc6766572c)

Should I open this as a new issue?
