### ISSUE TITLE
No config file present when building with Visual Studio

### ISSUE THREAD

**Issue by MarcoCoreDuo** [snesrev/zelda3#74]
When building with Visual Studio, you need to manually copy the config file into the release folder. I don't know if this is intended.

**Comment by Nutzzz** [comment]
Proposed fix in PR #76

**Comment by snesrev** [comment]
Someone could fix so the .exe ends up in the root directory instead. Preferably with names like zelda3_x86_debug or similar, with the release x64 version having the name zelda3.exe

**Comment by FitzRoyX** [comment]
I think it would be easier for nabs if the files required to run all get copied into an "out" folder instead of comingling with source files. It's not immediately obvious to such people that moving the exe somewhere else and not bringing the "saves" and "ini" stuff with it will result in problems.

**Comment by keatongreve** [comment]
Does this issue occur when building/running directly from Visual Studio? this might be due to a VS project configuration, but it's possible the working directory when zelda3.exe is run via VS would be the directory where the solution file is located (the repo root). If you were to execute it directly later, from the x64/Debug folder, it would expect a config file in that directory instead.

#76 might help, I'm not too sure since I haven't tested it. But it might be good to check if there are different outcomes for running from VS studio vs running the executable directly.

**Comment by snesrev** [comment]
Fxed so it chdirs to zelda3.ini in 6bd8b1185e7a9a1d80b4d9a10fbf6e04b767de4c
